spring.application.name=harshit-spring-ai
# Server
server.port=8080

# Spring AI - OpenAI
#spring.ai.openai.api-key=
spring.ai.openai.api-key=${OPENAI_API_KEY}


# PostgreSQL Database Connections
spring.datasource.url=jdbc:postgresql://localhost:5433/Progression?currentSchema=concept_planning
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Embedding model
spring.ai.openai.embedding.options.model=text-embedding-3-small

# Chat model
spring.ai.openai.chat.options.model=gpt-4o-mini

# ollama configuration
#spring.ai.ollama.base-url = http://localhost:11434
#spring.ai.ollama.chat.options.model= codellama:latest


# JWT Security
jwt.secret = "HarshitSpringAIJwtSecretKeyForDevelopmentOnlyChangeThisInProduction123456789"
jwt.access-token-expiration= 900000

#OPENAI_API_KEY= s@k-proj-BREI3SprHcNMyAI-BaU4o5M5mbhiWhQf_K-P8rM3v57YYzBgPX2hr6cbA4Uf2MEM1epwLdyZK9T3BlbkFJYxlj0xNhyepwIPs1dLFWmYGpeXJG0bc8bhkaKvNpv7HMb9eg54lrSdvFKAI_Ec_EopGQJgkb8A